### ISSUE TITLE
Parsing fails if PrimaryStore.xml contains Groovy or Jython scripts

### ISSUE THREAD

**Issue by mvenzke-axway** [lfirwin/axway-js-filter-check#1]
The current code seems to assume that only JavaScript is allowed, but Groovy and Jython scripts are also possible.[1]  I had to insert some logic like this to skip them instead of making pyjsparser die because it didn't understand them.  There may be a better way which is why I didn't send a PR.

        # Initialize empty list of alerts
        parsed_filter['alerts'] = []
        # ^ existing code for context

        # Only 'nashorn' and 'js' are JavaScript, ignore any other scripting filters!
        if parsed_filter['script_type'] != 'js' and parsed_filter['script_type'] != 'nashorn':
            logging.debug("Non-JS script found: " + parsed_filter['script_type'])
            continue

[1] https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_policydev/apigw_polref/utility_additional/index.html#scripting-language-filter

Error was:

Traceback (most recent call last):
  File "check_js.py", line 189, in <module>
    res = p.parse(parsed_filter['script'])
  File "C:\Python27\lib\site-packages\pyjsparser\parser.py", line 3010, in parse
    raise self.createError(self.lineNumber, self.lastIndex, unicode(e))
pyjsparser.pyjsparserdata.JsSyntaxError: Line 1: ImportDeclaration is not supported by ECMA 5.1.

Script snippet:

DEBUG:Entity Key: -1000000000000000000
DEBUG:Filter name: Sign Message
DEBUG:Engine name: groovy
DEBUG:------------------------------------------------------
DEBUG:import java.security.Signature;

**Comment by lfirwin** [comment]
Good catch!  This was purposed-built since our implementation just uses JavaScript. :)

Thanks for the feedback and testing.

**Comment by mvenzke-axway** [comment]
I was trying to use it on Windows, as well, but only managed a quick & dirty hack to make that work with -f PrimaryStore.xml by getting rid of the prepended / on it.

I think it only fails if you have Groovy scripts that use 'import' or something, a default FED with samples that I tried it on didn't fail.
